//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordUnscramblerAianSeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordUnscramblerAianSeb.Properties.stringEN", typeof(stringEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue? (y/n).
        /// </summary>
        internal static string Continuation {
            get {
                return ResourceManager.GetString("Continuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the space is blank, enter a value..
        /// </summary>
        internal static string emptyString {
            get {
                return ResourceManager.GetString("emptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the specified file..
        /// </summary>
        internal static string FalseFile {
            get {
                return ResourceManager.GetString("FalseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option was&apos;nt recognized.
        /// </summary>
        internal static string FalseOption {
            get {
                return ResourceManager.GetString("FalseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string IsMatch {
            get {
                return ResourceManager.GetString("IsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Words:.
        /// </summary>
        internal static string MatchedWord {
            get {
                return ResourceManager.GetString("MatchedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files cannot be found..
        /// </summary>
        internal static string NotFoundFile {
            get {
                return ResourceManager.GetString("NotFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full path with the file name.
        /// </summary>
        internal static string OptionF {
            get {
                return ResourceManager.GetString("OptionF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file for matching purposes.
        /// </summary>
        internal static string OptionF2 {
            get {
                return ResourceManager.GetString("OptionF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter word(s) manually or as a file F or Manual M.
        /// </summary>
        internal static string OptionM {
            get {
                return ResourceManager.GetString("OptionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a word to match.
        /// </summary>
        internal static string OptionM2 {
            get {
                return ResourceManager.GetString("OptionM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter scrambled words with File (F) or Manually (M).
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start over (y/n).
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re enter new files.
        /// </summary>
        internal static string Reenterfiles {
            get {
                return ResourceManager.GetString("Reenterfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new words.
        /// </summary>
        internal static string Reenterwords {
            get {
                return ResourceManager.GetString("Reenterwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words that you want to match.
        /// </summary>
        internal static string Wordstomatch {
            get {
                return ResourceManager.GetString("Wordstomatch", resourceCulture);
            }
        }
    }
}
