//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordUnscramblerAianSeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordUnscramblerAianSeb.Properties.stringFR", typeof(stringFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous continuer ? (o/n).
        /// </summary>
        internal static string Continuation {
            get {
                return ResourceManager.GetString("Continuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;espace est vide, veuillez entrer une valeur..
        /// </summary>
        internal static string emptyString {
            get {
                return ResourceManager.GetString("emptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de lire le fichier spécifié..
        /// </summary>
        internal static string FalseFile {
            get {
                return ResourceManager.GetString("FalseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;option n&apos;a pas été reconnue..
        /// </summary>
        internal static string FalseOptions {
            get {
                return ResourceManager.GetString("FalseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondances.
        /// </summary>
        internal static string IsMatch {
            get {
                return ResourceManager.GetString("IsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mots Correspondants :.
        /// </summary>
        internal static string MatchedWord {
            get {
                return ResourceManager.GetString("MatchedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ces fichiers ne peuvent pas être trouvés..
        /// </summary>
        internal static string NotFoundFile {
            get {
                return ResourceManager.GetString("NotFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le chemin complet avec le nom du fichier.
        /// </summary>
        internal static string OptionF {
            get {
                return ResourceManager.GetString("OptionF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez un fichier à des fins de correspondance.
        /// </summary>
        internal static string OptionF2 {
            get {
                return ResourceManager.GetString("OptionF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez des mots manuellement ou un fichier F ou Manuel M.
        /// </summary>
        internal static string OptionM {
            get {
                return ResourceManager.GetString("OptionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez un mot à faire correspondre.
        /// </summary>
        internal static string OptionM2 {
            get {
                return ResourceManager.GetString("OptionM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez des mots brouillés avec Fichier (F) ou Manuellement (M).
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous recommencer (o/n).
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réintroduisez de nouveaux fichiers.
        /// </summary>
        internal static string Reenterfiles {
            get {
                return ResourceManager.GetString("Reenterfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez de nouveaux mots.
        /// </summary>
        internal static string Reenterwords {
            get {
                return ResourceManager.GetString("Reenterwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots que vous souhaitez faire correspondre.
        /// </summary>
        internal static string Wordstomatch {
            get {
                return ResourceManager.GetString("Wordstomatch", resourceCulture);
            }
        }
    }
}
